-- file: elevator.vhd
-- Generated by MyHdL 0.8.1
-- date: Sun Jun 14 22:11:56 2015

library ieee;
  use ieee.std_logic_1164.all;
  use ieee.numeric_std.all;
  use std.textio.all;
  use work.pck_myhdl_081.all;

entity elevator is
  port (
    clk     : in    std_logic;
    reset   : in    std_logic;
    en      : in    std_logic;
    f       : in    unsigned(3 downto 0);
    d       : inout unsigned(3 downto 0);
    q       : inout unsigned(3 downto 0);
    a       : inout std_logic;
    b       : inout std_logic;
    a_latch : inout std_logic;
    b_latch : inout std_logic;
    led     : out   unsigned(3 downto 0)
  );
end entity elevator;

architecture myhdl of elevator is

begin

  elevator_encoder : process (en, f) is
  begin

    if (bool(f) and bool(en)) then
      a <= stdl(bool(f(3)) or (bool(f(1)) and (not bool(f(2)))));
      b <= stdl(bool(f(2)) or bool(f(3)));
    end if;

  end process elevator_encoder;

  elevator_latch : process (reset, a, b, en, f) is
  begin

    if bool(reset) then
      a_latch <= '0';
      b_latch <= '0';
    elsif (bool(f) and bool(en)) then
      a_latch <= a;
      b_latch <= b;
    end if;

  end process elevator_latch;

  d <= unsigned'((((not q(3)) and (not q(2)) and (not q(1)) and (not q(0)) and b_latch and a_latch) or ((not q(3)) and (not q(2)) and q(1) and (not q(0)) and (not b_latch) and (not a_latch)) or (q(3) and q(2) and q(1) and (not q(0))) or ((not q(3)) and (not q(2)) and q(1) and q(0) and (not b_latch))) &
                 (((not q(3)) and (not q(2)) and q(1) and q(0) and (not b_latch) and (not a_latch)) or ((not q(3)) and (not q(2)) and (not q(1)) and b_latch and a_latch) or (q(3) and q(2) and (not q(1)) and q(0)) or ((not q(3)) and (not q(2)) and (not q(1)) and (not q(0)) and b_latch)) &
                 (((not q(3)) and (not q(2)) and q(1) and q(0) and (not b_latch)) or ((not q(3)) and (not q(2)) and q(0) and b_latch) or (q(2) and (not q(1)) and q(0)) or ((not q(3)) and q(1) and (not q(0)) and b_latch) or ((not q(3)) and q(2) and q(1) and (not q(0)))) &
                 (((not q(3)) and (not q(2)) and q(1) and (not q(0)) and (not b_latch) and (not a_latch)) or ((not q(3)) and (not q(2)) and (not q(1)) and (not b_latch) and a_latch) or ((not q(3)) and (not q(2)) and q(1) and b_latch and a_latch) or ((not q(3)) and (not q(2)) and (not q(1)) and (not q(0)) and b_latch) or (q(3) and q(1) and (not q(0))) or ((not q(3)) and q(2) and q(1) and (not q(0))) or (q(1) and (not q(0)) and a_latch)));

  elevator_dff : process (clk, reset) is
  begin

    if (reset = '1') then
      q <= to_unsigned(0, 4);
    elsif rising_edge(clk) then
      if bool(en) then
        q <= d;
      end if;
    end if;

  end process elevator_dff;

  led <= unsigned'((q(1) and q(0)) &
                   (q(1) and (not q(0))) &
                   ((not q(1)) and q(0)) &
                   ((not q(1)) and (not q(0))));

end architecture myhdl;
